name: Publish GitBook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 8

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitBook
        run: |
          npm install -g gitbook-cli
          gitbook fetch

      - name: Build GitBook
        run: |
          gitbook build . ./docs

      - name: Deploy GitBook
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
